//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.Database
{
    using System;

    public partial class Product
    {
        private string _name;
        private string _description;
        private double? _price;
        private string _serialNo;
        private string _manufacturer;

        public System.Guid Id { get; private set; } = Guid.NewGuid();
        public string Name { get => _name; set => _name = value; }
        public string Description { get => _description; set => _description = value; }
        public Nullable<double> Price { get => _price; set => _price = value; }
        public string SerialNo { get => _serialNo; set => _serialNo = value; }
        public string Manufacturer { get => _manufacturer; set => _manufacturer = value; }
    }
}
